version: "3.7"

services: 
    database_rentalx:
        image: postgres
        container_name: database_rentalx
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=rentalx2021
            - POSTGRES_DB=rentalx
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentalx
        ports: 
            - 3333:3333
        links: 
            - database_rentalx
        depends_on: 
            - database_rentalx
        volumes: 
            - .:/usr/app
            - /usr/app/node_modules
volumes: 
    pgdata: